module.exports = {
  REALM_APP_ID: process.env.REACT_APP_REALM_APP_ID,
  STRIPE_API_KEY: process.env.REACT_APP_STRIPE_API_KEY,
  STRIPE_SERVER_URL: process.env.REACT_APP_STRIPE_SERVER_URL,
  AIRTABLE_SERVER_URL: process.env.REACT_APP_AIRTABLE_SERVER_URL,
  CHAT_API_SERVER_URL: process.env.REACT_APP_CHAT_API_SERVER_URL,
  STREAM_CHAT_API_KEY: process.env.REACT_APP_STREAM_CHAT_API_KEY,
}
